### ISSUE TITLE
Excluding files from shared-projects is not working anymore

### ISSUE THREAD

**Issue by JanSoundhouse** [saros-project/saros#1080]
Since Saros 16.0.1 its not possible anymore to exclude files from sharing.

In the share-project view the buttons to expand the project folder disappear up-on first click without expanding the project folder.
This makes it impossible to choose which files to exclude from sharing.

![Saros plugin](https://user-images.githubusercontent.com/21235713/89990488-c0662400-dc82-11ea-8a54-9380cc5493b2.png)

 - OS: Linux Ubuntu 18.04
 - IDE: Eclipse 2019-09 (4.13)
 - Saros Version[16.0.1]

**Comment by tobous** [comment]
This is not a bug but rather a feature we removed. "Partial sharing" (i.e. choosing which files to share from a project) caused a lot of issues with more complicated setups (see #31, #36, #44, #235, #256) and seemed more like a corner case to us than the default use case.

We are replacing the feature with allowing the user to choose which folder to share (independent of whether it is a project or not). This allows the user to precisely select the base folders they would like to share. But this will only be available with the next release, which will take a while.

In the meantime, you could mark the resource you do not want to share as "derived" (right-click them in the project view and select "Properties" from the context menu; under "Attributes", select the option "Derived"). This will also exclude them from the session (for now; this behavior is more of a workaround and might change with a future update as well).

The behavior of the dialog to select the resources is indeed a bug. This is due to the internal workaround we added to remove the partial sharing feature. The dialog removes all entries of the project tree besides the project elements itself. This seems to cause some kind of issue with the tree implementation provided by Eclipse, still showing the arrow to expand the view even though there are no child elements. Sorry for the confusion.
