### ISSUE TITLE
Using "Create New Project" option creates wrong directory structure 

### ISSUE THREAD

**Issue by srossbach** [saros-project/saros#1094]
Inviter folder _src_ of project _A_

On the receiving side select **Create New Project**

First issue: The suggested project name is _src_ although it should be _A_ .

After the project is created the directory layout does not match.

On the receiving side the _src_ folder is not present, instead the whole content of _src_ is directly placed under the project path. I am aware that this should actually be the case but regarding the logic so create a new **Project** this might not be very helpful.

**Comment by tobous** [comment]
As you already mentioned, this is the expected behavior of the logic.

If a user decides to share a folder `FOO`, they are _only_ sharing the folder and its contents. The receiving side does not know that that the folder is part of a project or where it is located in the project on the sender side. As a result, if the user chooses to create a new project on the receiving side, the shared folder is used as the project root.

I made this decision as I wanted to avoid introducing IDE-workspace-model-specific logic to the resource negotiation. As Eclipse does not allow mapping resources into the workspace without them being part of a project, I still had to offer the option to create a project as part of the resource negotiation. Otherwise, the user could be left in a state where the wizard could not be continued as the workspace is empty, meaning there are no resources present that can be used for the mapping.

I now see that it would have been better to offer an external option to create a project instead (as is present in the wizard to start a session). This would allow the user to manually create a new project in the workspace before continuing the wizard. As a result, we would no longer have to offer the option of creating a project as part of the negotiation. Instead, using an existing directory or creating a new directory would be the only available options. This should hopefully also remove any expectations that the negotiation correctly sets up projects.

@srossbach What do you think about this approach?

A drawback of this approach is that it would require the existing STF tests to be adjusted again as some still rely on the logic used to set up a new project. But this should hopefully not be too hard.

**Comment by srossbach** [comment]
You can already create a project in Eclipse as the dialog is non modal (I guess that do not help as it is not obvious).

I guess we can put this on hold for now as (at least me) we are lacking user data for common workflows.

As for the project creation. I guess that was a decision that was made long time ago in regards to the HTML GUI.

I still do not know if it is sufficient to just create them via the core as project configuration is IDE specific and has only worked so smoothly in Eclipse because we transmitted the _.project_ file and so Eclipse was auto updating the project nature etc. during the negotiation.
