### ISSUE TITLE
Strange behavior for overlapping objects

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#17]
OS: Windows XP
Eclipse: 3.6.2
Saros: 11.3.25-Testing

If you draw overlapping objects \(e.g. rectangles\) sometimes they appear as parts from each other and sometime they will be drawn independently.

Reported by: stephan808

Original Ticket: [dpp/bugs/483](https://sourceforge.net/p/dpp/bugs/483)

**Comment by AbdBarho** [comment]
this is technically a feature not a bug, if the drawing of the new shape starts in another shape, the new shape is regarded as a child of the older one, however, starting the drawing out of the old shape but overlapping it will be its own separate shape and appended directly to the root of the document.

this is not a problem in the html whiteboard since all shapes are added to the root directly, no children hierarchies.
