### ISSUE TITLE
Scenario for Git support in Saros 

### ISSUE THREAD

**Issue by chrismotian** [saros-project/saros#213]
I want to write a scenario to find the requirements for the Git support in Saros.
Even if up to now there is no Git support there is maybe a common sense about a workflow when you work with Saros and want to use Git. Please give me your opinion about this scenario.

Scenario: Creating a Commit
System under discussion: IDE with Saros Plugin
Primary actor: Alice 
Secondary actor: Bob
Goal: One new commit and moving branch to this commit for Alice and Bob
Conditions: two users in a session, both checkout at the same branch, same code on each side
Steps:
1. Alice click on commit
2. IDE commit to Alice's local repository
3. Bob discard changes since the pre-commit
4. Bob informs IDE to fetch from Alice's repository
5. IDE bring Bob's repository to the same code as Alice's. Bob also had the new commit under the same branch.

**Comment by donut87** [comment]
First of all: Great topic!
The scenario for creating a commit seems reasonable. There is one catch though: Alice has to make the local repo available. With ssh or http(s) does not make a difference, but it has to be reachable. This is where the tricky part is. Normally local repositories are not accessible from the outside and it can be tedious to establish (OS settings, company firewall, etc.).
So, on establishing the session it needs to be clear whether Alice's repo is available or not.

**Comment by chrismotian** [comment]
Thanks for your response and for the feedback! In respect to past work done here, I have to say that the idea to implement a Git support for Saros has not been done by me. 
To 'solve' the problems regarding the Git-Way accessing the local repo: "If none of the standard protocols between the two developers is possible, Saros could provide a bridge, e.g. if Alice and Bob are in a Saros session, Bob pulls from a "remote" repository at localhost: which is a proxy for Alice's Git repo -- the actual communication is done via Saros. "(http://www.inf.fu-berlin.de/w/SE/ThesesDPP#Git_45Support_f_195_188r_Saros_40B_44_M_41). Another way is to have a shared remote repo with access for Alice and Bob.

**Comment by donut87** [comment]
As I read it, this is planned work for the future. How does this ticket fit into this?
Is this aiming to be a temporal solution until a whole git process is implemented?
Is it a step in this direction?
Is it a feature that later can be integrated in a complete git process?

**Comment by chrismotian** [comment]
I will work on a Git support for Saros for the next 2 months because it is my Bachelor Thesis. I started with this scenario and I am working right now on finding test cases for "establishing a session with a Git project".

**Comment by tobous** [comment]
As a general note: During all of these procedures to sync up the git state, you would have to disable the Saros session/editor listeners for Bob, as the changes made while resetting the local state and the applying the commit (and possibly re-applying the rest of the local state) would be transferred to Alice. The end state should still be consistent, but this behavior would still be very confusing in my opinion.

#### Regarding the condition "both checkout at the same branch"

In my opinion, to just set the condition "both participants are on the same branch" is a bit lax as our actions might mess up the local branch for Bob if this condition is violated. This should be checked by Saros before trying to transmit the commit. (I would ignore the possible concurrency/TOCTOU problems for now. A branch change for Bob in this interval is very unlikely.)

#### Regarding step 3 - Bob discard changes since the pre-commit

I am not sure what exactly you mean by this. To apply the shared commit locally, Bob can not have any unstaged changes (I am not sure if any unstaged changes at all or only no unstaged changes that modify files also modified by the merged commits). This would mean we would have to discard at least some of Bob's changes.

But we don't want to discard all of Bob's changes as he might have other unstaged changes that are not in conflict with the merge.
This is not covered by the condition "same code on each side" as these unstaged changes can also be outside the scope of the Saros session, meaning Saros should not influence them at all.
This condition is to strict in general in my opinion, as it would also mean that all changes made during the session would have to be included in the commit. Otherwise, the remaining changes would be lost on Bob's side when discarding the local changes before applying the commit.

This would mean we would have to differentiate which untracked changes we would have to discard and which we would want to keep (or stash and re-apply after the merge if not untracked files are allowed at all). 

#### Regarding the solution with a shared repository and a coordinated push-pull:

A coordinated push-pull to a shared repository would be a solution, but you have to also consider that, depending on your git workflow, you may not always want to push to the repo when you make a commit or may not want to push to the branch you are currently on (e.g. because you created the commit on the current master locally).

A hacky solution to make this process branch-independent would be to create a temporary branch that is created by Alice.  The name of this branch is transferred from Alice to Bob using Saros. Bob could pull and subsequently delete this branch from the repo. Bob would then merge this temporary branch (with fast-forward) into the working branch. This should still keep the commit id intact for both Alice and Bob.
This basic approach would only work for sessions with two participants. A more general approach for a multi-user session would be that all participants notify the committer (or the host if notifying a client would be to much of a hassle with the Saros infrastructure), who then cleans up the temporary branch once all participants are done.

The main issue with this approach would be that we would have to make sure that the name for our temporary branch does not already exist in the repository.
A small drawback would also be that this procedure would create unnecessary "noise"/"spam" if the shared repository has some sort of notifications for pushes/branch creations.

#### Regarding the third suggested solution [on the linked page](http://www.inf.fu-berlin.de/w/SE/ThesesDPP#Git_45Support_f_195_188r_Saros_40B_44_M_41) - The Git-way (2)

I am not sure how this would work. To ensure that the created branch state is easily usable for Alice and Bob, the commit ID for the created commit has to match on both sides. This means we can't just transfer the commit diff through Saros and then create the commit locally on Bob's side. I am not sure if you can create an archive/diff of a commit that you can apply locally and that also generates the local commit with the initial commit id.

Or am I misunderstanding how you were intending to use Saros as the "proxy" for the git push/pull stuff?

**Comment by chrismotian** [comment]
@tobous First: Thanks for your answer.

Regarding the condition - "This should be checked by Saros" <- Am I understand this right: You suggest that Saros should check that both users are checkout at the same branch?

Regarding step 3 - The condition "same code on each side" regard the files that are in the scope of the action we are going to do (discard changes since pre-commit) Even if Saros just share partial, together with the condition "both checkout at the same branch" we can say that all files (in the Git scope) are equal. I will change the condition to "same code in the Git project on each side". This should be valid but maybe it's redundant with "both checkout at the same branch". It's worth mentioning that the .git folder isn't one of this files. 
Another important point: Because both users work together on the same files the commit only need to be done by only one of both and the other one will not make his own commit but just pull from the committer. **There will be no merge.** 

The temporary branch idea sounds useful and I will keep it in mind when after I stopped working on the problem and start working on the solution.

Regarding The Git-way (2) - I have added a Use Case #214 which regards another working step (starting a session) but there is mentioned an Option (Option D) which is using the same idea. Reading this should help to understand how this should work in my opinion.

**Comment by chrismotian** [comment]
> Transferring the hashsums using Saros 

I like this one!

**"discard changes since pre-commit"**
My idea behind that step was to prepare Bob that he is ready for a fast-forward merge. He should undo everything since the start of the session and together with the condition "same code on each side" I assumed that this cover all the scenarios. The scenario I have in my mind was that everything( file D and file E) are shared and in the Git Scope. But after reading your examples I realized that it can be more complicated.
The idea of using the stash sound reasonable to me. I will consider it. I'll keep it in mind.

**Regarding the question asked in #214 regarding sharing the ".git" folder with Saros**
I idea isn't to replace your .git folder but to transfer a copy of the committers .git folder and save it next to your own. This should be done by Saros's protocol instead of Git's because @donut87 assumed problems with them. 
>There is one catch though: Alice has to make the local repo available. With ssh or http(s) does not make a difference, but it has to be reachable. This is where the tricky part is. Normally local repositories are not accessible from the outside and it can be tedious to establish (OS settings, company firewall, etc.).
So, on establishing the session it needs to be clear whether Alice's repo is available or not.

You still have to use the git API to interact with the committers folder, but you just need access to a local repo, not a remote one.

**Comment by chrismotian** [comment]
After some discussions with git contributors regarding the topic "transfer the .git directory" I decided to don't transfer files from this directory. It needs very careful decisions about what to transfer and some extra work to don't override, but change the machine and developer specific files like for example the config file .In my opinion, by using the git API we can achieve the same much simpler. 

The discussion gives me another solution for sending around files the Saros way:
Use the `git bundle` command!
The idea is to bundle files by the host with git bundle, send the bundle via Saros to all-non hosts and then use the git API to access it locally.

**Comment by m273d15** [comment]
[`git bundle`](https://git-scm.com/book/en/v2/Git-Tools-Bundling) looks very promising:exclamation: It seems like this command does exactly what you wanted to do. The only question is which commits should be bundled.

**Comment by donut87** [comment]
I agree. Bundling seems exactly what you want to do. @m273d15 Which commit should be bundled is dependent on the use case. Whether there is a cloned repo present already on the other side or not and in which state it is.
Also, it might be possible to bundle each time a commit is done and send the bundle and recreate. That way the projects would be kept in sync using the direct connection without the hassle of opening up ssh or http(s) ports.

**Comment by chrismotian** [comment]
I have written a new use case to consider the command `git bundle`. To keep it short I will not write down the use case but ask you for your opinion for this selected case. If you want to check the Actors, Goals etc. please read #214 because the framework hasn't changed.
In this case, Bob hasn't worked on this project before. If Alice wants to share just some files that are inside the scope of the version control I would do it that way: Inform the user that he has to share the whole project (every file in the version control scope) if he wants to use the version control on the client side. An alternative way is to send the whole project as a bundle, clone it and delete the not-shared files afterward. This isn't reasonable for me. Deleting files on Bob's side creates different workspaces for Alice and Bob. This is something we shouldn't allow, in my opinion, because it creates problems. For example, Bob wants to commit. He will not create the same commit as Alice because he is missing some files. Both should create the same commit in my opinion.
