### ISSUE TITLE
Contribution annotation does not disappear

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#32]
What happened:

- Session with Julia, Franz, Stephan
- Julia opens a file (MUCManager.java from Saros sourcecode), selects and copies whole content and pastes it multipe times
- On Franz' side: Whole content is colored in Julia's color (blue)
- On Franz' side: Own changes don't have any color at all.
- Stephan joins, and makes a few changes
- On Franz' side: First, Stephan's changes are green, but after a few keystrokes they don't lose their color, instead they get blue, as if Julia's copy-paste actions have made blue the "Default Color".

See attached screenshot for Franz' view (was taken 12:45, thus the corresponding changes happend a few minutes before). 

Reported by: fzieris

Original Ticket: [dpp/bugs/757](https://sourceforge.net/p/dpp/bugs/757)

**Comment by srossbach** [comment]
I was able to reproduce this always.

First defect, the annotation is always inserted twice by the EditorManager.
The EditorManager assumes that there is no anntotation at the given point which can be wrong.

Easy to reproduce

Mark some character (more than 1, eg. 10). Copy and paste them into the same document.
Go somewhere in the middle between the copied text. Start to insert characters.

Result: Eclipse will auto expand the annotation however the ContributionAnnotationManager will not update the history nor insert the annotation because there is already a given annotation at the current position.

**Comment by srossbach** [comment]
![image](https://user-images.githubusercontent.com/41400679/63793820-c1caff00-c900-11e9-9971-8901800856c1.png)
