### ISSUE TITLE
Exclude patches dir from auto-formatting

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#322]
As @fzieris mentioned in #313 
> The files in the "patches" folder were always excluded from any auto-format commits. Those are "original" pieces of other projects' code with minor amendments. Auto-formatting these makes it way harder to see the actual "patch".

The following steps are required:
* Verify whether other directories are affected
* Adjust Travis CI formatting
* Adjust example git hook
* Undo formatting

**Comment by fzieris** [comment]
I never actually needed to reconstruct the original patch, though. Instead of engineering a work-around for not-auto-formatting some files, it might be better to think about the "patches" files themselves:
* Do current versions of our dependencies still need to be patched?
* Can we entice the original projects to incorporate our patches?
* Are there other options for Saros to get the desired functionality with unpatched dependencies, e.g. through more "common" ways such as sub-classing or wrapping?

**Comment by m273d15** [comment]
This task will be part of the upcoming dependency updates

I found an entry in the [patches/smack_patches_readme.txt](https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/patches/smack_patches_readme.txt) that implies that the patches was always part of the auto-formatting:
> If you delete the patches then you have to reapply them if they are not already fixed
in the updated SMACK version.

> As this mostly not work automatically because the file will get auto formated if you doing
changes the following steps are recommended.

**Comment by fzieris** [comment]
The readme refers to the actual *.patch file, not the *.java files.

* https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/patches/org/jivesoftware/smack/smack-312.patch 
* https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/patches/org/jivesoftware/smack/Roster.java
* https://github.com/saros-project/saros/blob/master/de.fu_berlin.inf.dpp.core/patches/org/jivesoftware/smack/RosterEntry.java

**Comment by fzieris** [comment]
Ah, I see, line 27: "Format them to apply our format rules." My bad.
