### ISSUE TITLE
Change versions for nightly releases

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#351]
In order to provide nightly releases which contain correct version numbers, it is necessary to change the version number automatically.

The version number is defined in:
* Saros/E `de.fu_berlin.inf.dpp/META-INF/MANIFEST.MF`
* Saros/I `de.fu_berlin.inf.dpp.intellij/META-INF/plugin.xml`
* Saros/Server has no version (for now)

For now the version would look like:
`<YY>.<MM>.<DD>.NIGHTLY` -> e.g. `18.12.11.NIGHTLY` or `DEVEL`

**Comment by tobous** [comment]
How about using the entire year to ensure that the versioning is not mistaken for semantic versioning as easily?
`<YYYY>.<MM>.<DD>.NIGHTLY>` -> e.g. `2018.12.11.NIGHTLY`

**Comment by m273d15** [comment]
I also prefer your format. I see no reason to use semantic versioning since we provide no API. @srossbach @stefaus Do you have a preference ?

**Comment by srossbach** [comment]
The core is an API, the Eclipse Plugin is an OSGi bundle (and OSGi uses semantic versioning). I highly suggest you only change the last part of the version (using the build number). This is a general issue for many developers. There is a difference between the version number that is visible to the user and the internal version number. Please keep in mind that we are already at major version 14 in Eclipse.

**Comment by tobous** [comment]
@srossbach The old Saros/E releases use the calendar versioning (or whatever it is officially called) as well. See our [old release instructions](http://www.saros-project.org/ReleaseProcess). A move to semantic versioning was planned but never realized.

The last release was just in 2014, which is why it is version 14.xx.xx. Exactly this confusion is why I would definitely prefer using the whole year when using calendar versioning.

**Comment by srossbach** [comment]
If you want to switch to semantic versioning you should stop using the calendar versioning for Eclipse. Even if these are nightly releases, I recommend not to install them if they are using these versioning numbers. So what is the problem to make a final cut now and use semantic versioning instead ?

**Comment by m273d15** [comment]
How would you represent the different feature sets of Saros/E and Saros/I in the semantic versioning? I was not sure whether semantic versioning could confuse the users if both plugins have the same version. Would you create separate versions for the plugins? e.g. the next Saros/E release will have the version 15.0 and the first release of Saros/E will be 1.0-Alpha ?

**Comment by tobous** [comment]
The big question is which versioning we want to use. What I tried to convey was that a move to semantic versioning was planned *previously* (there is a TODO for this on the release page).

Which versioning scheme we should use going forwards still needs to be discussed.
With calendar versioning, you loose the general information on which kinds changes to expect when updating. On the other hand, we would somehow have to keep a consistent versioning scheme for all Saros versions, meaning at least the major versions of Saros/I and Saros/E (and probably also the minor versions) would have to be related once we reach feature parity. This would make it somewhat complicated.

Stefan, could you be more precise what the problem is with using calendar versioning with Saros/E ( or rather OSGi bundles)?

**Comment by srossbach** [comment]
The problem with the OSGi stuff is that you could (if you versioning it right) release some bug fixes to certain plugins without having to update every plugin. As the Core is luckily still at version 1.0 this is not the problem. However the Whiteboard is tight to a fixed Saros Eclipse number, i.e it always use the highest version of the plugin. So if you update only the Saros Plugin it is likely that the Whiteboard will not work any longer.

As for the version schema. The basic functionality is defined by the core. Last but not least. We can still say this is IntelliJ and Eclipse Version 18 (2018). It is only up to us to define the correct dependencies, e.g Version 18 uses Core Version X.Y.Z and Saros Eclipse A.B.C
