### ISSUE TITLE
proxy support issue. establish working proxy support

### ISSUE THREAD

**Issue by dpp-gerrit** [saros-project/saros#43]
There are known issues with proxy support in saros.
We relied on SMACK who seem to have a problem.

This request reminds of issuing and re-enabling proxy support, which is going to be turned off for the time being.

Reported by: michaelsdev

Original Ticket: [dpp/bugs/805](https://sourceforge.net/p/dpp/bugs/805)

**Comment by srossbach** [comment]
Anyone have a clue what this issue is about ? I could only guess that this is some HTTP Proxy stuff used in conjunction with XMPP, i.e you are using a HTTP proxy to establish a to an XMPP server.

**Comment by tobous** [comment]
Maybe they meant the Socks5 proxy option (which allows us to use the XMPP server as a socks5 proxy)?

If that is the case we can probably close this ticket as this option is currently enabled and seems to be working fine. We rely on it when creating a Saros session in the university network as the firewall blocks direct connections between clients (as this otherwise would take forever due to timeouts).

**Comment by srossbach** [comment]
Still wondering why technical/administration stuff resides in the issue tracker. Yes we can either provider a Socks5Proxy are we can just ensure that IBB connections are configured with an acceptable bandwidth.

**Comment by srossbach** [comment]
Socks5 proxy for actually establishing a connection to the XMPPServer was added back years ago. We only disabled HTTP proxy support as it uncommon to tunnel long living connections through HTTP.
