### ISSUE TITLE
Improve separation between IDE specific documentation on website

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#593]
Currently, the sections that require IDE specific details (like installation or usage instructions) are split into different pages (e.g. [eclipse installation](https://www.saros-project.org/documentation/installation-eclipse.html) and [intellij installation](https://www.saros-project.org/documentation/installation-intellij.html).

This separation creates a lot of clutter in the navbar and makes it much harder to navigate the site or find the needed page.

A suggested alternative would be to split such pages into different tabs, each containing the detailed information for an implementation. This would also introduce better scalability when adding information for other implementations (like the server).
The biggest issue with this approach is that we need the user to notice the tabs, as they otherwise make the site harder to navigate instead of easier.

**Comment by m273d15** [comment]
First proposal on my gh-page instance [here](https://m273d15.github.io/saros/documentation/getting-started.html) and [here](https://m273d15.github.io/saros/documentation/installation.html).
* Uses tabs in order to differentiate between different saros documentation flavors
* Switches the whole content if one tab is clicked (if we have just small boxes of IDE specific content it is possible to click on "eclipse" and all other boxes also show the "eclipse" content)

Known flaws:
* TOC is broken (might be be hard to fix! The current toc is created statically via native Jekyll commands. The new solution either requires to create two tocs and the js selects the current one or the toc has to be created dynamically)
* Not cite-able (It is currently not possible to reference a documentation flavor via url). Should be fixable with a js workaround.

Is this a usable approach? Any design proposals? @Drakulix already proposed to use an IDE specific border color. I am not sure whether the tabs are to big and should be shrinked. Otherwise:
> The biggest issue with this approach is that we need the user to notice the tabs, as they otherwise make the site harder to navigate instead of easier.

**Comment by tobous** [comment]
I am not sure how this would look, but for readability, I would suggest moving the tabs to the left side. This would allow the reader to naturally come across the tabs when following the website-flow (nav-bar -> headline -> text).

Also as a side note: Currently, the tab that is *not* actually selected is highlighted as such (blue text). This is kind of confusing as it is opposite to the rest of the side (see nav-bar), where blue highlighting implies selection.

I think I would prefer a dynamically changing TOC. But that is just a first thought as this most likely has to be experimented with to figure out whether it is actually usable or just confusing. Can you approximate how much work such a dynamic TOC would take?

As an alternative, could you include the TOC in the tab? This way the tab would act more like a sub-page.

**Comment by m273d15** [comment]
I will the fix the mentioned issue and create a WIP PR which we can use to discuss the design. 

> Can you approximate how much work such a dynamic TOC would take?

You are right the dynamic version should be the way to go. A static + dynamic version would lead to a very confusing implementation. I think I would try to adopt an existing solution as [markdown-toc](https://www.npmjs.com/package/markdown-toc). This should be easy (not "hard to fix").

> As an alternative, could you include the TOC in the tab? This way the tab would act more like a sub-page.

You can have multiple tabs in one page. Therefore the TOC should be outside of the tab.
