### ISSUE TITLE
Rename Saros/E annotation color settings

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#634]
Saros/E offers settings to customize the colors that annotations are shown in.
The settings are located in the settings under "General" > "Editors" > "Text Editors" > "Annotations".

The names of the different entries are outdated, i.e. they still start with "DPP". This should be changed to "Saros" to avoid confusion as the shorthand DPP is no longer used by the project.

**Comment by srossbach** [comment]
The settings are automatically provided by Eclipse. We do not need to write any line of code. Since the settings you made there will be overwritten by us every time on plugin start I recommend to not showing them at all (which can be easily done be settings a key for every annotation in the plugin.xml to false).

Any reasons for showing them ?

**Comment by tobous** [comment]
Well it depends on whether we replace them or not. I still think it is beneficial to allow the users to customize the used colors. I was not aware that the settings made there are dropped every time the IDE is restarted.

If the settings are replaced by an alternative settings page (which you already suggested in #632), these options can probably be just removed if they are completely obsoleted. If, however, there are still some options in the menu that we won't include in our settings page, it could still be useful to offer such options, even if just in a temporary fashion.

**Comment by srossbach** [comment]
You got me wrong. As our plugin resets the values (not Eclipse) it is currently the best option to hide them. We also have annotations that will be never shown there because this annotations are managed by us (to be more specific we draw them on the widgets). 

https://github.com/saros-project/saros/blob/master/eclipse/src/saros/editor/annotations/SelectionFillUpStrategy.java

**Comment by tobous** [comment]
Hmmm. That is indeed a problem.

But I am still not blown away by removing a customization option (even if it is not *that* usable) without offering a replacement.

**Comment by srossbach** [comment]
![image](https://user-images.githubusercontent.com/41400679/62782618-e9c20200-baba-11e9-8b06-f61fd1d2d087.png)

Using this mechanism is not great for picking colors. Especially setting 15 of them.

**Comment by srossbach** [comment]
And IIRC there was once an option to set colors (however it was coded so badly that it was also setting the color on the remote side). It got removed, using only a default color set for everyone.

**Comment by tobous** [comment]
Using default sets would certainly help.

But, with eclipse also supporting (custom) color themes, it would be nigh impossible to provide an option that is usable with every color scheme. So I still think that allowing the user to customize the colors is important.

**Comment by srossbach** [comment]
The problem I have ( I do not know how it is handled in IntelliJ). The colors you can choose when Saros asks you are based on the Contribution color. So when you let the user manually change the colors you can end up with the contribution color GREEN, highlight color BLUE and viewport color RED.

So Saros will you offer color GREEN for User 0, however its other colors are not just a lighter GREEN but completely different. I would also have to lookup and possibly remove code where color brightness is adjusted because we tested it with the given hardcoded values but we do not know how it will look like when the user can choose its own colors.

**Comment by tobous** [comment]
In Saros/I, there currently only are two annotations: contribution annotations and selection annotations.  So there are only two colors per color id.
By default, the default Saros colors are used, but each available color can be chosen by the user. As the settings are integrated into IntelliJ, the chosen values are automatically saved.
With more colors, having to adjust every one could be cumbersome, but I still think its acceptable as long as the default colors are usable for the default themes.

There is no logic  that automatically determines colors based on other choices or that manipulates brightness. And, since the users can choose colors, brightness, etc. themselves, I wouldn't worry about the visibility with custom colors as it's their own fault if they can't see anything.

In my opinion this also goes for Saros/E: If the users can customize everything, we shouldn't worry about having shitty color combinations when they are customized as this is up to the user. Only the default colors should be chosen carefully.

**Comment by tobous** [comment]
Fixed by #636.
