### ISSUE TITLE
Saros in VSCode via LSP

### ISSUE THREAD

**Issue by m273d15** [saros-project/saros#729]
The approach of @mschaefer88 is to implement the language server protocol (lsp) in order to
implement a Saros support in VSCode.

I would like to track the uncertainty whether this approach allows a stable implementation.
We have to clarify the following issues:
- [ ] Does the lsp allow to run multiple language server (ls) for one language (e.g. for java: java-ls and saros-ls)
- [ ] Does the lsp allow to run a language agnostic ls?

**Comment by m273d15** [comment]
@mschaefer88 I have some general questions and things we should keep in mind concerning the approach. Therefore, I created the issue. Probably both questions are easy two answer, but I think is is necessary two answer them.
I found the following [issue](https://github.com/Microsoft/language-server-protocol/issues/636) concerning the multi-language support. It might helpful.

**Comment by mschaefer88** [comment]
> The approach of @mschaefer88 is to implement the language server protocol (lsp) in order to
> implement a Saros support in VSCode.
> 
> I would like to track the uncertainty whether this approach allows a stable implementation.
> We have to clarify the following issues:
> 

* [x]  Does the lsp allow to run multiple language server (ls) for one language (e.g. for java: java-ls and saros-ls)
Yes it does, since each language support using language server will bring its own client.
See [example](https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-multi-server-sample).
* [x]  Does the lsp allow to run a language agnostic ls?
Yes it does, wether the client is used or not depends on the extension activation which can be set to ***** which means activated on start. Therefore we're not bound to any language.

**Comment by m273d15** [comment]
:+1:
