### ISSUE TITLE
Broken XMPP Account Creation / In-band registration

### ISSUE THREAD

**Issue by stefaus** [saros-project/saros#787]
#### State of XMPP Account Creation / In-band registration:
- Disabled for Saros XMPP Server
  - [Saros Documentation](https://www.saros-project.org/documentation/getting-started.html?tab=eclipse)
    - Picture with "Create New Account" button is misleading
    - Did anyone test if gmail still works for xmpp?
      - Advising users to set "allow less secure apps access your account" seems sketchy
      - reading [XMPP with Google Hangouts](https://github.com/linuxcsuf/linuxcsuf/wiki/XMPP-with-Google-Hangouts) it looks broken
- Eclipse: Button for In-band registration in "Add XMPP Account" Dialog was removed, but not from Menu (Saros -> Create Account) and not from "Start Saros Configuration" Wizard
- In-band registration Dialog 
  - only working for Servers without Captchas (and allowed in-band) -> is broken for nearly all cases
  - freezes (Eclipse) if the xmpp-server is not available until connection times out (~2 min.)
  - Help Button links to 404 webpage (see #620)
- [`CreateXMPPAccountWizard`](https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/wizards/CreateXMPPAccountWizard.java) and [`CreateXMPPAccountWizardPage`](https://github.com/saros-project/saros/blob/master/eclipse/src/saros/ui/wizards/pages/CreateXMPPAccountWizardPage.java) are Eclipse Dialog classes which do xmpp Error Handling, using Smack objects, ... and would need to be moved to core

#### Proposals:
- remove google xmpp from docs
- complete removal of in-band registration classes and add link to the last working git-commit in some `package-info.java` file
- add information text to "Add Account" and "Start Saros Configuration" regarding Saros XMPP registration page
- find someone to update website pictures

@m273d15 @tobous @srossbach Are you ok with this removal?

**Comment by srossbach** [comment]
I cannot agree with the "Error Handling" stuff. There is no error handling in the UI code. It just generated human readable messages (yes it looks ugly is not very elegant because of real missing error codes).

I do not even know why this feature was added at all because it is obvious that IBR is normally disabled in a public environment (at least without using captchas).

**Comment by tobous** [comment]
#### Regarding IBR

I am somewhat torn on the removal of IBR. It currently does not work and leads to weird issues, but having it working would be a very valuable feature for the ease of use. It is so much easier to have everything packaged in the application rather then having to look for and head to a separate website for account creation. (Furthermore, the current account creation website does not look very credible. It is *very* bare bones and looks kind of sketchy.)

So it would be nice to implement IBR captcha support *in the client* (i.e. the captcha and the entry field are seamlessly integrated into the account creation wizard displayed by the IDE). But I don't know how much effort this would take.

Furthermore, speaking with regards to our long term planning, IBR seems more like a specific XMPP protocol feature to me rather then a common network protocol feature. So it might get in the way when we are trying to abstract from the used network protocol.

#### Regarding the human readable error messages

For me, this very much depends on the cause of the error and the content of the created messages.
If neither the cause nor the contents are IDE specific (i.e. are the same for all IDEs), I would lean towards moving them to the core so that we don't have to do the "parsing" for every IDE implementation. Furthermore, it helps keeping a unified experience (i.e. similar error messages) between IDE implementations, making debugging/error analysis a lot easier.

But that is also something that should be discussed as part of the "core ui package" debate.

**Comment by srossbach** [comment]
Implementing IBR correctly (with our outdated Smack library) may take a good bunch of work. 

Basically you have to parse the registration info send by the server and then present it in some nice form. 

Also there are different kinds of captchas (e.g voice captchas) that could be used.

Just presenting the image should not be hard. However do you think that is is worth to add such an feature which will require at least 1 full week to develop and in the end is not used very frequently ?

**Comment by tobous** [comment]
> Also there are different kinds of captchas (e.g voice captchas) that could be used.
>
> Just presenting the image should not be hard. However do you think that is is worth to add such an feature which will require at least 1 full week to develop and in the end is not used very frequently ?

I didn't think about other forms of captchas. I guess it is not worth it investing that much time into providing IBR that only sometimes works. So its removal from the code base is fine with me. (If we ever were to decide to re-implemented it, we can still have a look at the history anyways.)

@stefaus That mean there aren't any issue with the initial proposal from my point of view. `+1` from me.

**Comment by stefaus** [comment]
I think Image Captcha and Hashcash would be sufficient but, I looked into implementing this with our current Smack Version but this would be a hacky solution and not worth the effort.
Now instead of a hard removal, I added a switch and uncommented code which will make it easier to reenable IBR after updating smack.
See #807 for this.

**Comment by stefaus** [comment]
IBR is removed / disabled with #807
