### ISSUE TITLE
Connection establishment settings for "IBB only" also sets "Socks5 Proxy only" 

### ISSUE THREAD

**Issue by tobous** [saros-project/saros#90]
In the Saros network settings ("Saros" > "Network"), the option "Only establish connections over IBB" also seems to set the setting "Only establish connections over an external Socks5 Proxy Server".

The "Only Socks5 Proxy" option is initially grayed out (can't be toggled) when the option "Only IBB" is enabled. After the settings are applied and the menu is re-opened, the option "Only Socks5 Proxy" is still grayed out (not click-able) but it is now also enabled.
If the option "Only IBB" is now disabled, it is subsequently grayed out while the "Only Socks5 Proxy" option still remains enabled but is now no longer grayed out.

I don't know whether this is only a display bug or whether the option for "Only Socks5 Proxy" is really enabled.

### Steps to reproduce:
1. Open the preferences and navigate to "Saros" > "Network"
2. Tick the checkbox "Only establish connections over IBB [only very small bandwidth is guaranteed]".
3. Click "Apply" and then exit the preferences window (by clicking "Apply and close" or the equivalent button).
4. Re-open the preferences menu and navigate to "Saros" > "Network"

**Comment by m273d15** [comment]
The issue with the checkbox states was caused by the following logic:
FORCE_FILETRANSFER_BY_CHAT is true if "Only IBB" is checked
LOCAL_SOCKS5_PROXY_DISABLED is true if "Only Socks5 Proxy" or "Only IBB" is checked

And the value of the checkbox "Only Socks5 Proxy" is set corresponding to the value
of LOCAL_SOCKS5_PROXY_DISABLED. Therefore the checkbox is also set if "Only IBB" is checked.

The checkbox "Only Socks5 Proxy" should only be set if FORCE_FILETRANSFER_BY_CHAT/FORCE_IBB_CONNECTIONS
is false and LOCAL_SOCKS5_PROXY_DISABLED is true.

This solution should also work if the Saros version is updated, because only the reading part is adjusted.
